### ISSUE TITLE
Highlights from My Clippings.txt is not syncing anymore

### ISSUE THREAD

**Issue by vivsbandhu** [arkalim/kindle-to-notion#22]
Hi @arkalim , 

I just setup the kindle-to-notion sync but everytime I run the workflow, nothing gets synced to Notion and I see the following in the log: 
📋 Parsing Clippings

➕ Grouping Clippings

💹 Stats for Clippings
--------------------------------------
🟢 Every book is already synced!
--------------------------------------

But nothing really gets synced to Notion DB. Could you please help me debug this issue? 

Thanks!

**Comment by arkalim** [comment]
Can you try deleting the `sync.json` file present in your clipping repository? That should fix the issue.

**Comment by saimohan149** [comment]
Hi @arkalim
Facing the same issue even after deleting the sync.json file.

**Comment by vivsbandhu** [comment]
Tried after deleting. Didn't work. Also updated the date format from 24hrs to 12hrs as was mentioned in some older thread, that too didn't help. The issue still exists :(

**Comment by brigante88** [comment]
same problem, no sync

**Comment by arkalim** [comment]
Can you share your clipping file? I'll take a look.

**Comment by vivsbandhu** [comment]
[My Clippings_original.txt](https://github.com/arkalim/kindle-to-notion/files/11436662/My.Clippings_original.txt)
@arkalim here you go.

**Comment by vivsbandhu** [comment]
Hi @arkalim , any updates on the above issue. Eager to get my kindle notes on Notion. Thanks!

**Comment by arkalim** [comment]
Hi, I've updated the code (fixed the regex). It should work now.
